

```{r}
#Get Started
setwd("~/Desktop/Capstone Keys/Keys Data/FL_BRUVS")
BRUVS_variables <- read.csv("BRUVS.Variables.csv")

#rename species groups for sharks and rays to elasmo
elasmo <- BRUVS_variables[BRUVS_variables$species_group== "Shark" | BRUVS_variables$species_group== "Ray", ]
elasmo$species <- as.factor(elasmo$species) #Fix species column to be a factor
elasmo
#need to fix the rest of the columns that need to be factors, change time to character
#Species column nd dealing with unidentified species. 
unique(elasmo$species)
elasmo[which(elasmo$species=="sp."), ] #call up "sp."
which(elasmo$genus=="Rhizoprionodon") #call up sharpnose genus
elasmo[which(elasmo$genus=="Rhizoprionodon"), ] #is this the same things as line 29?
levels(elasmo$species) <- c(levels(elasmo$species), "sharpnose") #what is a level? 
elasmo$species[which(elasmo$genus=="Rhizoprionodon")] <- "sharpnose" #rename genus to sharpnose becuase none were identified at the species level. 

#call up the data set without the last unidentified species and rename elasmo (note: ! stands for not equal to)
elasmo <- elasmo[which(elasmo$species!="sp."), ]
elasmo[which(elasmo$species=="sp."), ]
```

```{r}
# Looking at the data structure 
View(BRUVS_variables)
ls(BRUVS_variables)

#how many BRUVS there are
length(unique(BRUVS_variables$set_code))
```

```{r}
#histograms of individual data sets for numeric varaibles
hist(BRUVS_variables$depth)
hist(BRUVS_variables$DIST_MPA)
hist(BRUVS_variables$DIST_COASTLINE)
hist(BRUVS_variables$depth)
hist(BRUVS_variables$visibility)

#need to fix this! Is it not working because its a decimal and time? 
hist(BRUVS_variables$event_time_mins)

#qqnorm plots variables
qqnorm(BRUVS_variables$depth)
qqnorm(BRUVS_variables$DIST_MPA)
qqnorm(BRUVS_variables$DIST_COASTLINE)
qqnorm(BRUVS_variables$depth)
qqnorm(BRUVS_variables$visibility)
```

```{r}
#how many BRUVS there are 
length(unique(BRUVS_variables$set_code))
#336

#how many BRUVS saw elasmos
length(unique(elasmo$set_code))
#165

#counts of observations
maxn.freq <-  table(elasmo$maxn)
visibility.freq <- table(elasmo$visibility)
year.freq <- table(BRUVS_variables$trip_year)
species.freq <- table(elasmo$species)
com_name.freq <- table(elasmo$common_name)

maxn.freq
visibility.freq
year.freq
species.freq
com_name.freq

#I think we need to change the reef name because some regions overlap but have different names

reef_freq <- table(BRUVS_variables$reef_name)
reef_freq

#bar plot of species by common name and scientific 
#I think we might need to change some of the common names to be consistent (ex: hammerhead, great hammerhaed)
barplot(com_name.freq, main="common_name",
   xlab="Number of Individuals Identified")
barplot(species.freq, main="species",
   xlab="Number of Individuals Identified")

```


```{r}
#plots of variables. Are these the right types of plots to use? Why does sp. still show up as a column? 
plot(elasmo$species, elasmo$maxn)
plot(elasmo$species, elasmo$depth)
plot(elasmo$species, elasmo$DIST_MPA)
plot(elasmo$species, elasmo$DIST_COASTLINE)
plot(elasmo$species, elasmo$visibility)
plot(elasmo$species, elasmo$Percentage_Reef_Habitat_100m)

plot(elasmo$depth, elasmo$maxn, xlab = "depth (m)", ylab = "maxn")

#Can I plot depth and number of species seen? Same with % of reef, visibility, etc...

#need to plot other variables

```

```{r}

#is this something I need to do? 
cor.test(elasmo$maxn, elasmo$depth)
Model1 <- lm(elasmo$maxn~elasmo$depth)
summary(Model1)

```

